### ISSUE TITLE
想问一下 现在取embedding是有三种。想问一下token和label对齐 还是如BERT论文中说的那个方法吗？

### ISSUE THREAD

**Issue by xuanzebi** [Adaxry/get_aligned_BERT_emb#1]
就是BIEOS  然后不预测的为X？
![image](https://user-images.githubusercontent.com/26642184/63502641-957a4180-c500-11e9-9585-51efaea6100f.png)

想问一下有没有更好地方法呢

**Comment by Adaxry** [comment]
BERT论文里采用的方式即为“first”策略，在我们的实验中，mean > max > first

**Comment by xuanzebi** [comment]
想问一下 mean 和 max 这两种方法是怎么wordpiece划分后的token是怎么标注的呀

**Comment by xuanzebi** [comment]
理解了...
我一直想的是微调 
好像你们只是取出来特征后 然后融合进了RNN中。
GET了

我现在想NER微调来做一下，所以label也需要相应的变一下
